name: Release in GitHub repository

on:
  workflow_dispatch:

  push:
    branches: [ develop ]

jobs:

  release-github:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v4

      - name: Gradle Wrapper Validation
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build plugin
        run: ./gradlew buildPlugin

      - name: Update uploadPlugins.xml file
        uses: elveselimoski/intellij-update-plugins-xml-action@v0.1.0
        with:
          version: "0.1.0"
          url: "https://www.test.com/plugin.zip"

      # - name: Create plugin directory
      #   run: |
      #     mkdir -p plugin-repository
      #     cp build/distributions/*.zip plugin-repository/
      #   # cp updatePlugins.xml plugin-repository/

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./plugin-repository
      #     publish_branch: gh-pages
      #     force_orphan: true